/**
 * BKDLL 国家清单 + 9 区分组
 * 数据源：PTZONE2025.pdf 第 1 页（DHL 出口分区，BKDLL 沿用）
 *
 * 字段：
 *   cn   - 中文国家名（UI 显示）
 *   code - ISO 3166-1 二字代码（传给易抵达 API 的 toCustomer.countryCode）
 *   zone - BKDLL 1~9 区
 */

window.BKDLL_COUNTRIES = [
  // ===== 第 1 区：港澳 =====
  { cn: "中国香港", code: "HK", zone: 1 },
  { cn: "中国澳门", code: "MO", zone: 1 },

  // ===== 第 2 区：韩国、台湾 =====
  { cn: "韩国", code: "KR", zone: 2 },
  { cn: "中国台湾", code: "TW", zone: 2 },

  // ===== 第 3 区：日本 =====
  { cn: "日本", code: "JP", zone: 3 },

  // ===== 第 4 区：东南亚 =====
  { cn: "文莱", code: "BN", zone: 4 },
  { cn: "印度尼西亚", code: "ID", zone: 4 },
  { cn: "柬埔寨", code: "KH", zone: 4 },
  { cn: "老挝", code: "LA", zone: 4 },
  { cn: "马来西亚", code: "MY", zone: 4 },
  { cn: "菲律宾", code: "PH", zone: 4 },
  { cn: "新加坡", code: "SG", zone: 4 },
  { cn: "泰国", code: "TH", zone: 4 },
  { cn: "越南", code: "VN", zone: 4 },

  // ===== 第 5 区：澳新 =====
  { cn: "澳大利亚", code: "AU", zone: 5 },
  { cn: "新西兰", code: "NZ", zone: 5 },

  // ===== 第 6 区：北美 =====
  { cn: "加拿大", code: "CA", zone: 6 },
  { cn: "墨西哥", code: "MX", zone: 6 },
  { cn: "美国", code: "US", zone: 6 },

  // ===== 第 7 区：欧洲 =====
  { cn: "安道尔", code: "AD", zone: 7 },
  { cn: "奥地利", code: "AT", zone: 7 },
  { cn: "比利时", code: "BE", zone: 7 },
  { cn: "保加利亚", code: "BG", zone: 7 },
  { cn: "瑞士", code: "CH", zone: 7 },
  { cn: "塞浦路斯", code: "CY", zone: 7 },
  { cn: "捷克", code: "CZ", zone: 7 },
  { cn: "德国", code: "DE", zone: 7 },
  { cn: "丹麦", code: "DK", zone: 7 },
  { cn: "爱沙尼亚", code: "EE", zone: 7 },
  { cn: "西班牙", code: "ES", zone: 7 },
  { cn: "芬兰", code: "FI", zone: 7 },
  { cn: "法国", code: "FR", zone: 7 },
  { cn: "英国", code: "GB", zone: 7 },
  { cn: "根西岛", code: "GG", zone: 7 },
  { cn: "直布罗陀", code: "GI", zone: 7 },
  { cn: "格陵兰岛", code: "GL", zone: 7 },
  { cn: "希腊", code: "GR", zone: 7 },
  { cn: "克罗地亚", code: "HR", zone: 7 },
  { cn: "匈牙利", code: "HU", zone: 7 },
  { cn: "加那利群岛", code: "IC", zone: 7 },
  { cn: "爱尔兰", code: "IE", zone: 7 },
  { cn: "印度", code: "IN", zone: 7 },
  { cn: "冰岛", code: "IS", zone: 7 },
  { cn: "意大利", code: "IT", zone: 7 },
  { cn: "泽西岛", code: "JE", zone: 7 },
  { cn: "列支敦士登", code: "LI", zone: 7 },
  { cn: "立陶宛", code: "LT", zone: 7 },
  { cn: "卢森堡", code: "LU", zone: 7 },
  { cn: "拉脱维亚", code: "LV", zone: 7 },
  { cn: "摩纳哥", code: "MC", zone: 7 },
  { cn: "马耳他", code: "MT", zone: 7 },
  { cn: "荷兰", code: "NL", zone: 7 },
  { cn: "挪威", code: "NO", zone: 7 },
  { cn: "波兰", code: "PL", zone: 7 },
  { cn: "葡萄牙", code: "PT", zone: 7 },
  { cn: "瑞典", code: "SE", zone: 7 },
  { cn: "斯洛文尼亚", code: "SI", zone: 7 },
  { cn: "斯洛伐克", code: "SK", zone: 7 },
  { cn: "圣马力诺", code: "SM", zone: 7 },
  { cn: "梵蒂冈", code: "VA", zone: 7 },

  // ===== 第 8 区：中东 =====
  { cn: "阿拉伯联合酋长国", code: "AE", zone: 8 },
  { cn: "巴林", code: "BH", zone: 8 },
  { cn: "埃及", code: "EG", zone: 8 },
  { cn: "以色列", code: "IL", zone: 8 },
  { cn: "科威特", code: "KW", zone: 8 },
  { cn: "沙特阿拉伯", code: "SA", zone: 8 },
  { cn: "土耳其", code: "TR", zone: 8 },

  // ===== 第 9 区：其他（拉美、非洲、中亚、其他岛屿等）=====
  { cn: "阿富汗", code: "AF", zone: 9 },
  { cn: "安提瓜", code: "AG", zone: 9 },
  { cn: "安圭拉", code: "AI", zone: 9 },
  { cn: "阿尔巴尼亚", code: "AL", zone: 9 },
  { cn: "亚美尼亚", code: "AM", zone: 9 },
  { cn: "安哥拉", code: "AO", zone: 9 },
  { cn: "阿根廷", code: "AR", zone: 9 },
  { cn: "美属萨摩亚", code: "AS", zone: 9 },
  { cn: "阿鲁巴", code: "AW", zone: 9 },
  { cn: "阿塞拜疆", code: "AZ", zone: 9 },
  { cn: "波斯尼亚和黑塞哥维那", code: "BA", zone: 9 },
  { cn: "巴巴多斯", code: "BB", zone: 9 },
  { cn: "孟加拉", code: "BD", zone: 9 },
  { cn: "布基纳法索", code: "BF", zone: 9 },
  { cn: "布隆迪", code: "BI", zone: 9 },
  { cn: "贝宁", code: "BJ", zone: 9 },
  { cn: "百慕大", code: "BM", zone: 9 },
  { cn: "玻利维亚", code: "BO", zone: 9 },
  { cn: "巴西", code: "BR", zone: 9 },
  { cn: "巴哈马", code: "BS", zone: 9 },
  { cn: "不丹", code: "BT", zone: 9 },
  { cn: "博茨瓦那", code: "BW", zone: 9 },
  { cn: "白俄罗斯", code: "BY", zone: 9 },
  { cn: "伯利兹", code: "BZ", zone: 9 },
  { cn: "刚果民主共和国", code: "CD", zone: 9 },
  { cn: "中非共和国", code: "CF", zone: 9 },
  { cn: "刚果", code: "CG", zone: 9 },
  { cn: "科特迪瓦", code: "CI", zone: 9 },
  { cn: "库克群岛", code: "CK", zone: 9 },
  { cn: "智利", code: "CL", zone: 9 },
  { cn: "喀麦隆", code: "CM", zone: 9 },
  { cn: "哥伦比亚", code: "CO", zone: 9 },
  { cn: "哥斯达黎加", code: "CR", zone: 9 },
  { cn: "古巴", code: "CU", zone: 9 },
  { cn: "佛得角", code: "CV", zone: 9 },
  { cn: "吉布提", code: "DJ", zone: 9 },
  { cn: "多米尼克", code: "DM", zone: 9 },
  { cn: "多米尼加共和国", code: "DO", zone: 9 },
  { cn: "阿尔及利亚", code: "DZ", zone: 9 },
  { cn: "厄瓜多尔", code: "EC", zone: 9 },
  { cn: "厄立特里亚", code: "ER", zone: 9 },
  { cn: "埃塞俄比亚", code: "ET", zone: 9 },
  { cn: "斐济群岛", code: "FJ", zone: 9 },
  { cn: "福克兰群岛", code: "FK", zone: 9 },
  { cn: "密克罗尼西亚", code: "FM", zone: 9 },
  { cn: "法罗群岛", code: "FO", zone: 9 },
  { cn: "加蓬", code: "GA", zone: 9 },
  { cn: "格林纳达", code: "GD", zone: 9 },
  { cn: "格鲁吉亚", code: "GE", zone: 9 },
  { cn: "法属圭亚那", code: "GF", zone: 9 },
  { cn: "加纳", code: "GH", zone: 9 },
  { cn: "冈比亚", code: "GM", zone: 9 },
  { cn: "几内亚", code: "GN", zone: 9 },
  { cn: "瓜德罗普", code: "GP", zone: 9 },
  { cn: "赤道几内亚", code: "GQ", zone: 9 },
  { cn: "危地马拉", code: "GT", zone: 9 },
  { cn: "关岛", code: "GU", zone: 9 },
  { cn: "几内亚比绍", code: "GW", zone: 9 },
  { cn: "圭亚那", code: "GY", zone: 9 },
  { cn: "洪都拉斯", code: "HN", zone: 9 },
  { cn: "海地", code: "HT", zone: 9 },
  { cn: "伊拉克", code: "IQ", zone: 9 },
  { cn: "伊朗", code: "IR", zone: 9 },
  { cn: "牙买加", code: "JM", zone: 9 },
  { cn: "约旦", code: "JO", zone: 9 },
  { cn: "肯尼亚", code: "KE", zone: 9 },
  { cn: "吉尔吉斯斯坦", code: "KG", zone: 9 },
  { cn: "基里巴斯", code: "KI", zone: 9 },
  { cn: "科摩罗", code: "KM", zone: 9 },
  { cn: "圣基茨", code: "KN", zone: 9 },
  { cn: "朝鲜", code: "KP", zone: 9 },
  { cn: "科索沃", code: "XK", zone: 9 },
  { cn: "开曼群岛", code: "KY", zone: 9 },
  { cn: "哈萨克斯坦", code: "KZ", zone: 9 },
  { cn: "黎巴嫩", code: "LB", zone: 9 },
  { cn: "圣卢西亚岛", code: "LC", zone: 9 },
  { cn: "斯里兰卡", code: "LK", zone: 9 },
  { cn: "利比里亚", code: "LR", zone: 9 },
  { cn: "莱索托", code: "LS", zone: 9 },
  { cn: "利比亚", code: "LY", zone: 9 },
  { cn: "摩洛哥", code: "MA", zone: 9 },
  { cn: "摩尔多瓦", code: "MD", zone: 9 },
  { cn: "黑山", code: "ME", zone: 9 },
  { cn: "马达加斯加", code: "MG", zone: 9 },
  { cn: "马绍尔群岛", code: "MH", zone: 9 },
  { cn: "北马其顿", code: "MK", zone: 9 },
  { cn: "马里", code: "ML", zone: 9 },
  { cn: "缅甸", code: "MM", zone: 9 },
  { cn: "蒙古", code: "MN", zone: 9 },
  { cn: "北马里亚纳群岛", code: "MP", zone: 9 },
  { cn: "马提尼克", code: "MQ", zone: 9 },
  { cn: "毛里塔尼亚", code: "MR", zone: 9 },
  { cn: "蒙特塞拉特岛", code: "MS", zone: 9 },
  { cn: "毛里求斯", code: "MU", zone: 9 },
  { cn: "马尔代夫", code: "MV", zone: 9 },
  { cn: "马拉维", code: "MW", zone: 9 },
  { cn: "莫桑比克", code: "MZ", zone: 9 },
  { cn: "纳米比亚", code: "NA", zone: 9 },
  { cn: "新喀里多尼亚", code: "NC", zone: 9 },
  { cn: "尼日尔", code: "NE", zone: 9 },
  { cn: "尼日利亚", code: "NG", zone: 9 },
  { cn: "尼加拉瓜", code: "NI", zone: 9 },
  { cn: "尼泊尔", code: "NP", zone: 9 },
  { cn: "瑙鲁", code: "NR", zone: 9 },
  { cn: "纽埃岛", code: "NU", zone: 9 },
  { cn: "阿曼", code: "OM", zone: 9 },
  { cn: "巴拿马", code: "PA", zone: 9 },
  { cn: "秘鲁", code: "PE", zone: 9 },
  { cn: "大溪地", code: "PF", zone: 9 },
  { cn: "巴布亚新几内亚", code: "PG", zone: 9 },
  { cn: "巴基斯坦", code: "PK", zone: 9 },
  { cn: "波多黎各", code: "PR", zone: 9 },
  { cn: "帕劳", code: "PW", zone: 9 },
  { cn: "巴拉圭", code: "PY", zone: 9 },
  { cn: "卡塔尔", code: "QA", zone: 9 },
  { cn: "留尼汪岛", code: "RE", zone: 9 },
  { cn: "罗马尼亚", code: "RO", zone: 9 },
  { cn: "塞尔维亚", code: "RS", zone: 9 },
  { cn: "俄罗斯", code: "RU", zone: 9 },
  { cn: "卢旺达", code: "RW", zone: 9 },
  { cn: "所罗门群岛", code: "SB", zone: 9 },
  { cn: "塞舌尔", code: "SC", zone: 9 },
  { cn: "苏丹", code: "SD", zone: 9 },
  { cn: "圣赫勒拿岛", code: "SH", zone: 9 },
  { cn: "塞拉利昂", code: "SL", zone: 9 },
  { cn: "塞内加尔", code: "SN", zone: 9 },
  { cn: "索马里", code: "SO", zone: 9 },
  { cn: "苏里南", code: "SR", zone: 9 },
  { cn: "南苏丹共和国", code: "SS", zone: 9 },
  { cn: "圣多美和普林西比", code: "ST", zone: 9 },
  { cn: "萨尔瓦多", code: "SV", zone: 9 },
  { cn: "叙利亚", code: "SY", zone: 9 },
  { cn: "斯威士兰", code: "SZ", zone: 9 },
  { cn: "特克斯和凯科斯群岛", code: "TC", zone: 9 },
  { cn: "乍得", code: "TD", zone: 9 },
  { cn: "多哥", code: "TG", zone: 9 },
  { cn: "塔吉克斯坦", code: "TJ", zone: 9 },
  { cn: "东帝汶", code: "TL", zone: 9 },
  { cn: "土库曼斯坦", code: "TM", zone: 9 },
  { cn: "突尼斯", code: "TN", zone: 9 },
  { cn: "汤加", code: "TO", zone: 9 },
  { cn: "特立尼达和多巴哥", code: "TT", zone: 9 },
  { cn: "图瓦卢", code: "TV", zone: 9 },
  { cn: "坦桑尼亚", code: "TZ", zone: 9 },
  { cn: "乌克兰", code: "UA", zone: 9 },
  { cn: "乌干达", code: "UG", zone: 9 },
  { cn: "乌拉圭", code: "UY", zone: 9 },
  { cn: "乌兹别克斯坦", code: "UZ", zone: 9 },
  { cn: "圣文森特岛", code: "VC", zone: 9 },
  { cn: "委内瑞拉", code: "VE", zone: 9 },
  { cn: "英属维尔京群岛", code: "VG", zone: 9 },
  { cn: "美属维尔京群岛", code: "VI", zone: 9 },
  { cn: "瓦努阿图", code: "VU", zone: 9 },
  { cn: "萨摩亚", code: "WS", zone: 9 },
  { cn: "伯奈尔", code: "BQ", zone: 9 },
  { cn: "库拉索", code: "CW", zone: 9 },
  { cn: "圣马丁", code: "MF", zone: 9 },
  { cn: "索马里兰", code: "XS", zone: 9 },
  { cn: "也门", code: "YE", zone: 9 },
  { cn: "马约特岛", code: "YT", zone: 9 },
  { cn: "南非", code: "ZA", zone: 9 },
  { cn: "赞比亚", code: "ZM", zone: 9 },
  { cn: "津巴布韦", code: "ZW", zone: 9 }
];

window.BKDLL_ZONE_NAMES = {
  1: "1区 · 港澳",
  2: "2区 · 韩国/台湾",
  3: "3区 · 日本",
  4: "4区 · 东南亚",
  5: "5区 · 澳新",
  6: "6区 · 北美",
  7: "7区 · 欧洲",
  8: "8区 · 中东",
  9: "9区 · 其他"
};
