/**
 * BKDLL 国家清单 + 9 区分组（中英双语）
 * 数据源：PTZONE2025.pdf 第 1 页
 *
 * 字段：cn / en / code / zone
 */

window.BKDLL_COUNTRIES = [
  // 第 1 区
  { cn: "中国香港", en: "Hong Kong", code: "HK", zone: 1 },
  { cn: "中国澳门", en: "Macau", code: "MO", zone: 1 },

  // 第 2 区
  { cn: "韩国", en: "South Korea", code: "KR", zone: 2 },
  { cn: "中国台湾", en: "Taiwan", code: "TW", zone: 2 },

  // 第 3 区
  { cn: "日本", en: "Japan", code: "JP", zone: 3 },

  // 第 4 区
  { cn: "文莱", en: "Brunei", code: "BN", zone: 4 },
  { cn: "印度尼西亚", en: "Indonesia", code: "ID", zone: 4 },
  { cn: "柬埔寨", en: "Cambodia", code: "KH", zone: 4 },
  { cn: "老挝", en: "Laos", code: "LA", zone: 4 },
  { cn: "马来西亚", en: "Malaysia", code: "MY", zone: 4 },
  { cn: "菲律宾", en: "Philippines", code: "PH", zone: 4 },
  { cn: "新加坡", en: "Singapore", code: "SG", zone: 4 },
  { cn: "泰国", en: "Thailand", code: "TH", zone: 4 },
  { cn: "越南", en: "Vietnam", code: "VN", zone: 4 },

  // 第 5 区
  { cn: "澳大利亚", en: "Australia", code: "AU", zone: 5 },
  { cn: "新西兰", en: "New Zealand", code: "NZ", zone: 5 },

  // 第 6 区
  { cn: "加拿大", en: "Canada", code: "CA", zone: 6 },
  { cn: "墨西哥", en: "Mexico", code: "MX", zone: 6 },
  { cn: "美国", en: "United States", code: "US", zone: 6 },

  // 第 7 区
  { cn: "安道尔", en: "Andorra", code: "AD", zone: 7 },
  { cn: "奥地利", en: "Austria", code: "AT", zone: 7 },
  { cn: "比利时", en: "Belgium", code: "BE", zone: 7 },
  { cn: "保加利亚", en: "Bulgaria", code: "BG", zone: 7 },
  { cn: "瑞士", en: "Switzerland", code: "CH", zone: 7 },
  { cn: "塞浦路斯", en: "Cyprus", code: "CY", zone: 7 },
  { cn: "捷克", en: "Czech Republic", code: "CZ", zone: 7 },
  { cn: "德国", en: "Germany", code: "DE", zone: 7 },
  { cn: "丹麦", en: "Denmark", code: "DK", zone: 7 },
  { cn: "爱沙尼亚", en: "Estonia", code: "EE", zone: 7 },
  { cn: "西班牙", en: "Spain", code: "ES", zone: 7 },
  { cn: "芬兰", en: "Finland", code: "FI", zone: 7 },
  { cn: "法国", en: "France", code: "FR", zone: 7 },
  { cn: "英国", en: "United Kingdom", code: "GB", zone: 7 },
  { cn: "根西岛", en: "Guernsey", code: "GG", zone: 7 },
  { cn: "直布罗陀", en: "Gibraltar", code: "GI", zone: 7 },
  { cn: "格陵兰岛", en: "Greenland", code: "GL", zone: 7 },
  { cn: "希腊", en: "Greece", code: "GR", zone: 7 },
  { cn: "克罗地亚", en: "Croatia", code: "HR", zone: 7 },
  { cn: "匈牙利", en: "Hungary", code: "HU", zone: 7 },
  { cn: "加那利群岛", en: "Canary Islands", code: "IC", zone: 7 },
  { cn: "爱尔兰", en: "Ireland", code: "IE", zone: 7 },
  { cn: "印度", en: "India", code: "IN", zone: 7 },
  { cn: "冰岛", en: "Iceland", code: "IS", zone: 7 },
  { cn: "意大利", en: "Italy", code: "IT", zone: 7 },
  { cn: "泽西岛", en: "Jersey", code: "JE", zone: 7 },
  { cn: "列支敦士登", en: "Liechtenstein", code: "LI", zone: 7 },
  { cn: "立陶宛", en: "Lithuania", code: "LT", zone: 7 },
  { cn: "卢森堡", en: "Luxembourg", code: "LU", zone: 7 },
  { cn: "拉脱维亚", en: "Latvia", code: "LV", zone: 7 },
  { cn: "摩纳哥", en: "Monaco", code: "MC", zone: 7 },
  { cn: "马耳他", en: "Malta", code: "MT", zone: 7 },
  { cn: "荷兰", en: "Netherlands", code: "NL", zone: 7 },
  { cn: "挪威", en: "Norway", code: "NO", zone: 7 },
  { cn: "波兰", en: "Poland", code: "PL", zone: 7 },
  { cn: "葡萄牙", en: "Portugal", code: "PT", zone: 7 },
  { cn: "瑞典", en: "Sweden", code: "SE", zone: 7 },
  { cn: "斯洛文尼亚", en: "Slovenia", code: "SI", zone: 7 },
  { cn: "斯洛伐克", en: "Slovakia", code: "SK", zone: 7 },
  { cn: "圣马力诺", en: "San Marino", code: "SM", zone: 7 },
  { cn: "梵蒂冈", en: "Vatican City", code: "VA", zone: 7 },

  // 第 8 区
  { cn: "阿拉伯联合酋长国", en: "United Arab Emirates", code: "AE", zone: 8 },
  { cn: "巴林", en: "Bahrain", code: "BH", zone: 8 },
  { cn: "埃及", en: "Egypt", code: "EG", zone: 8 },
  { cn: "以色列", en: "Israel", code: "IL", zone: 8 },
  { cn: "科威特", en: "Kuwait", code: "KW", zone: 8 },
  { cn: "沙特阿拉伯", en: "Saudi Arabia", code: "SA", zone: 8 },
  { cn: "土耳其", en: "Turkey", code: "TR", zone: 8 },

  // 第 9 区
  { cn: "阿富汗", en: "Afghanistan", code: "AF", zone: 9 },
  { cn: "安提瓜", en: "Antigua", code: "AG", zone: 9 },
  { cn: "安圭拉", en: "Anguilla", code: "AI", zone: 9 },
  { cn: "阿尔巴尼亚", en: "Albania", code: "AL", zone: 9 },
  { cn: "亚美尼亚", en: "Armenia", code: "AM", zone: 9 },
  { cn: "安哥拉", en: "Angola", code: "AO", zone: 9 },
  { cn: "阿根廷", en: "Argentina", code: "AR", zone: 9 },
  { cn: "美属萨摩亚", en: "American Samoa", code: "AS", zone: 9 },
  { cn: "阿鲁巴", en: "Aruba", code: "AW", zone: 9 },
  { cn: "阿塞拜疆", en: "Azerbaijan", code: "AZ", zone: 9 },
  { cn: "波斯尼亚和黑塞哥维那", en: "Bosnia and Herzegovina", code: "BA", zone: 9 },
  { cn: "巴巴多斯", en: "Barbados", code: "BB", zone: 9 },
  { cn: "孟加拉", en: "Bangladesh", code: "BD", zone: 9 },
  { cn: "布基纳法索", en: "Burkina Faso", code: "BF", zone: 9 },
  { cn: "布隆迪", en: "Burundi", code: "BI", zone: 9 },
  { cn: "贝宁", en: "Benin", code: "BJ", zone: 9 },
  { cn: "百慕大", en: "Bermuda", code: "BM", zone: 9 },
  { cn: "玻利维亚", en: "Bolivia", code: "BO", zone: 9 },
  { cn: "巴西", en: "Brazil", code: "BR", zone: 9 },
  { cn: "巴哈马", en: "Bahamas", code: "BS", zone: 9 },
  { cn: "不丹", en: "Bhutan", code: "BT", zone: 9 },
  { cn: "博茨瓦那", en: "Botswana", code: "BW", zone: 9 },
  { cn: "白俄罗斯", en: "Belarus", code: "BY", zone: 9 },
  { cn: "伯利兹", en: "Belize", code: "BZ", zone: 9 },
  { cn: "刚果民主共和国", en: "DR Congo", code: "CD", zone: 9 },
  { cn: "中非共和国", en: "Central African Republic", code: "CF", zone: 9 },
  { cn: "刚果", en: "Congo", code: "CG", zone: 9 },
  { cn: "科特迪瓦", en: "Cote d'Ivoire", code: "CI", zone: 9 },
  { cn: "库克群岛", en: "Cook Islands", code: "CK", zone: 9 },
  { cn: "智利", en: "Chile", code: "CL", zone: 9 },
  { cn: "喀麦隆", en: "Cameroon", code: "CM", zone: 9 },
  { cn: "哥伦比亚", en: "Colombia", code: "CO", zone: 9 },
  { cn: "哥斯达黎加", en: "Costa Rica", code: "CR", zone: 9 },
  { cn: "古巴", en: "Cuba", code: "CU", zone: 9 },
  { cn: "佛得角", en: "Cape Verde", code: "CV", zone: 9 },
  { cn: "吉布提", en: "Djibouti", code: "DJ", zone: 9 },
  { cn: "多米尼克", en: "Dominica", code: "DM", zone: 9 },
  { cn: "多米尼加共和国", en: "Dominican Republic", code: "DO", zone: 9 },
  { cn: "阿尔及利亚", en: "Algeria", code: "DZ", zone: 9 },
  { cn: "厄瓜多尔", en: "Ecuador", code: "EC", zone: 9 },
  { cn: "厄立特里亚", en: "Eritrea", code: "ER", zone: 9 },
  { cn: "埃塞俄比亚", en: "Ethiopia", code: "ET", zone: 9 },
  { cn: "斐济群岛", en: "Fiji", code: "FJ", zone: 9 },
  { cn: "福克兰群岛", en: "Falkland Islands", code: "FK", zone: 9 },
  { cn: "密克罗尼西亚", en: "Micronesia", code: "FM", zone: 9 },
  { cn: "法罗群岛", en: "Faroe Islands", code: "FO", zone: 9 },
  { cn: "加蓬", en: "Gabon", code: "GA", zone: 9 },
  { cn: "格林纳达", en: "Grenada", code: "GD", zone: 9 },
  { cn: "格鲁吉亚", en: "Georgia", code: "GE", zone: 9 },
  { cn: "法属圭亚那", en: "French Guiana", code: "GF", zone: 9 },
  { cn: "加纳", en: "Ghana", code: "GH", zone: 9 },
  { cn: "冈比亚", en: "Gambia", code: "GM", zone: 9 },
  { cn: "几内亚", en: "Guinea", code: "GN", zone: 9 },
  { cn: "瓜德罗普", en: "Guadeloupe", code: "GP", zone: 9 },
  { cn: "赤道几内亚", en: "Equatorial Guinea", code: "GQ", zone: 9 },
  { cn: "危地马拉", en: "Guatemala", code: "GT", zone: 9 },
  { cn: "关岛", en: "Guam", code: "GU", zone: 9 },
  { cn: "几内亚比绍", en: "Guinea-Bissau", code: "GW", zone: 9 },
  { cn: "圭亚那", en: "Guyana", code: "GY", zone: 9 },
  { cn: "洪都拉斯", en: "Honduras", code: "HN", zone: 9 },
  { cn: "海地", en: "Haiti", code: "HT", zone: 9 },
  { cn: "伊拉克", en: "Iraq", code: "IQ", zone: 9 },
  { cn: "伊朗", en: "Iran", code: "IR", zone: 9 },
  { cn: "牙买加", en: "Jamaica", code: "JM", zone: 9 },
  { cn: "约旦", en: "Jordan", code: "JO", zone: 9 },
  { cn: "肯尼亚", en: "Kenya", code: "KE", zone: 9 },
  { cn: "吉尔吉斯斯坦", en: "Kyrgyzstan", code: "KG", zone: 9 },
  { cn: "基里巴斯", en: "Kiribati", code: "KI", zone: 9 },
  { cn: "科摩罗", en: "Comoros", code: "KM", zone: 9 },
  { cn: "圣基茨", en: "Saint Kitts", code: "KN", zone: 9 },
  { cn: "朝鲜", en: "North Korea", code: "KP", zone: 9 },
  { cn: "科索沃", en: "Kosovo", code: "XK", zone: 9 },
  { cn: "开曼群岛", en: "Cayman Islands", code: "KY", zone: 9 },
  { cn: "哈萨克斯坦", en: "Kazakhstan", code: "KZ", zone: 9 },
  { cn: "黎巴嫩", en: "Lebanon", code: "LB", zone: 9 },
  { cn: "圣卢西亚岛", en: "Saint Lucia", code: "LC", zone: 9 },
  { cn: "斯里兰卡", en: "Sri Lanka", code: "LK", zone: 9 },
  { cn: "利比里亚", en: "Liberia", code: "LR", zone: 9 },
  { cn: "莱索托", en: "Lesotho", code: "LS", zone: 9 },
  { cn: "利比亚", en: "Libya", code: "LY", zone: 9 },
  { cn: "摩洛哥", en: "Morocco", code: "MA", zone: 9 },
  { cn: "摩尔多瓦", en: "Moldova", code: "MD", zone: 9 },
  { cn: "黑山", en: "Montenegro", code: "ME", zone: 9 },
  { cn: "马达加斯加", en: "Madagascar", code: "MG", zone: 9 },
  { cn: "马绍尔群岛", en: "Marshall Islands", code: "MH", zone: 9 },
  { cn: "北马其顿", en: "North Macedonia", code: "MK", zone: 9 },
  { cn: "马里", en: "Mali", code: "ML", zone: 9 },
  { cn: "缅甸", en: "Myanmar", code: "MM", zone: 9 },
  { cn: "蒙古", en: "Mongolia", code: "MN", zone: 9 },
  { cn: "北马里亚纳群岛", en: "Northern Mariana Islands", code: "MP", zone: 9 },
  { cn: "马提尼克", en: "Martinique", code: "MQ", zone: 9 },
  { cn: "毛里塔尼亚", en: "Mauritania", code: "MR", zone: 9 },
  { cn: "蒙特塞拉特岛", en: "Montserrat", code: "MS", zone: 9 },
  { cn: "毛里求斯", en: "Mauritius", code: "MU", zone: 9 },
  { cn: "马尔代夫", en: "Maldives", code: "MV", zone: 9 },
  { cn: "马拉维", en: "Malawi", code: "MW", zone: 9 },
  { cn: "莫桑比克", en: "Mozambique", code: "MZ", zone: 9 },
  { cn: "纳米比亚", en: "Namibia", code: "NA", zone: 9 },
  { cn: "新喀里多尼亚", en: "New Caledonia", code: "NC", zone: 9 },
  { cn: "尼日尔", en: "Niger", code: "NE", zone: 9 },
  { cn: "尼日利亚", en: "Nigeria", code: "NG", zone: 9 },
  { cn: "尼加拉瓜", en: "Nicaragua", code: "NI", zone: 9 },
  { cn: "尼泊尔", en: "Nepal", code: "NP", zone: 9 },
  { cn: "瑙鲁", en: "Nauru", code: "NR", zone: 9 },
  { cn: "纽埃岛", en: "Niue", code: "NU", zone: 9 },
  { cn: "阿曼", en: "Oman", code: "OM", zone: 9 },
  { cn: "巴拿马", en: "Panama", code: "PA", zone: 9 },
  { cn: "秘鲁", en: "Peru", code: "PE", zone: 9 },
  { cn: "大溪地", en: "Tahiti", code: "PF", zone: 9 },
  { cn: "巴布亚新几内亚", en: "Papua New Guinea", code: "PG", zone: 9 },
  { cn: "巴基斯坦", en: "Pakistan", code: "PK", zone: 9 },
  { cn: "波多黎各", en: "Puerto Rico", code: "PR", zone: 9 },
  { cn: "帕劳", en: "Palau", code: "PW", zone: 9 },
  { cn: "巴拉圭", en: "Paraguay", code: "PY", zone: 9 },
  { cn: "卡塔尔", en: "Qatar", code: "QA", zone: 9 },
  { cn: "留尼汪岛", en: "Reunion", code: "RE", zone: 9 },
  { cn: "罗马尼亚", en: "Romania", code: "RO", zone: 9 },
  { cn: "塞尔维亚", en: "Serbia", code: "RS", zone: 9 },
  { cn: "俄罗斯", en: "Russia", code: "RU", zone: 9 },
  { cn: "卢旺达", en: "Rwanda", code: "RW", zone: 9 },
  { cn: "所罗门群岛", en: "Solomon Islands", code: "SB", zone: 9 },
  { cn: "塞舌尔", en: "Seychelles", code: "SC", zone: 9 },
  { cn: "苏丹", en: "Sudan", code: "SD", zone: 9 },
  { cn: "圣赫勒拿岛", en: "Saint Helena", code: "SH", zone: 9 },
  { cn: "塞拉利昂", en: "Sierra Leone", code: "SL", zone: 9 },
  { cn: "塞内加尔", en: "Senegal", code: "SN", zone: 9 },
  { cn: "索马里", en: "Somalia", code: "SO", zone: 9 },
  { cn: "苏里南", en: "Suriname", code: "SR", zone: 9 },
  { cn: "南苏丹共和国", en: "South Sudan", code: "SS", zone: 9 },
  { cn: "圣多美和普林西比", en: "Sao Tome and Principe", code: "ST", zone: 9 },
  { cn: "萨尔瓦多", en: "El Salvador", code: "SV", zone: 9 },
  { cn: "叙利亚", en: "Syria", code: "SY", zone: 9 },
  { cn: "斯威士兰", en: "Eswatini", code: "SZ", zone: 9 },
  { cn: "特克斯和凯科斯群岛", en: "Turks and Caicos", code: "TC", zone: 9 },
  { cn: "乍得", en: "Chad", code: "TD", zone: 9 },
  { cn: "多哥", en: "Togo", code: "TG", zone: 9 },
  { cn: "塔吉克斯坦", en: "Tajikistan", code: "TJ", zone: 9 },
  { cn: "东帝汶", en: "Timor-Leste", code: "TL", zone: 9 },
  { cn: "土库曼斯坦", en: "Turkmenistan", code: "TM", zone: 9 },
  { cn: "突尼斯", en: "Tunisia", code: "TN", zone: 9 },
  { cn: "汤加", en: "Tonga", code: "TO", zone: 9 },
  { cn: "特立尼达和多巴哥", en: "Trinidad and Tobago", code: "TT", zone: 9 },
  { cn: "图瓦卢", en: "Tuvalu", code: "TV", zone: 9 },
  { cn: "坦桑尼亚", en: "Tanzania", code: "TZ", zone: 9 },
  { cn: "乌克兰", en: "Ukraine", code: "UA", zone: 9 },
  { cn: "乌干达", en: "Uganda", code: "UG", zone: 9 },
  { cn: "乌拉圭", en: "Uruguay", code: "UY", zone: 9 },
  { cn: "乌兹别克斯坦", en: "Uzbekistan", code: "UZ", zone: 9 },
  { cn: "圣文森特岛", en: "Saint Vincent", code: "VC", zone: 9 },
  { cn: "委内瑞拉", en: "Venezuela", code: "VE", zone: 9 },
  { cn: "英属维尔京群岛", en: "British Virgin Islands", code: "VG", zone: 9 },
  { cn: "美属维尔京群岛", en: "U.S. Virgin Islands", code: "VI", zone: 9 },
  { cn: "瓦努阿图", en: "Vanuatu", code: "VU", zone: 9 },
  { cn: "萨摩亚", en: "Samoa", code: "WS", zone: 9 },
  { cn: "伯奈尔", en: "Bonaire", code: "BQ", zone: 9 },
  { cn: "库拉索", en: "Curacao", code: "CW", zone: 9 },
  { cn: "圣马丁", en: "Saint Martin", code: "MF", zone: 9 },
  { cn: "索马里兰", en: "Somaliland", code: "XS", zone: 9 },
  { cn: "也门", en: "Yemen", code: "YE", zone: 9 },
  { cn: "马约特岛", en: "Mayotte", code: "YT", zone: 9 },
  { cn: "南非", en: "South Africa", code: "ZA", zone: 9 },
  { cn: "赞比亚", en: "Zambia", code: "ZM", zone: 9 },
  { cn: "津巴布韦", en: "Zimbabwe", code: "ZW", zone: 9 }
];

window.BKDLL_ZONE_NAMES = {
  1: "1区 · 港澳",
  2: "2区 · 韩国/台湾",
  3: "3区 · 日本",
  4: "4区 · 东南亚",
  5: "5区 · 澳新",
  6: "6区 · 北美",
  7: "7区 · 欧洲",
  8: "8区 · 中东",
  9: "9区 · 其他"
};
